##############################################################################
# Copyright (c) 2019 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
cluster:
  domain: mcp-k8s-calico-noha.local
  states:
    - kubernetes
virtual:
  nodes:
    control:
      - ctl01
    compute:
      - cmp001
      - cmp002
  ctl01:
    vcpus: 8
    ram: 14336
  cmp001:
    vcpus: 6
    ram: 12288
  cmp002:
    vcpus: 6
    ram: 12288
