##############################################################################
# Copyright (c) 2019 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
cluster:
  domain: mcp-iec-noha.local
  states:
    - virtual_control_plane
    - akraino_iec
virtual:
  nodes:
    control:
      - kvm01
      - kvm02
      - kvm03
  kvm01:
    vcpus: 8
    ram: 10240
  kvm02:
    vcpus: 8
    ram: 10240
  kvm03:
    vcpus: 8
    ram: 10240
