##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
cluster:
  domain: mcp-fdio-noha.local
  states:
    - openstack_noha
    - neutron_gateway
    - networks
virtual:
  nodes:
    control:
      - ctl01
      - gtw01
    compute:
      - cmp001
      - cmp002
  ctl01:
    vcpus: 4
    ram: 14336
  gtw01:
    vcpus: 8
    ram: 8192
    cpu_topology:
      sockets: 1
      cores: 4
      threads: 2
    numa:
      cell0:
        memory: 8388608
        cpus: 0-7
  cmp001:
    vcpus: 8
    ram: 8192
    cpu_topology:
      sockets: 1
      cores: 4
      threads: 2
    numa:
      cell0:
        memory: 8388608
        cpus: 0-7
  cmp002:
    vcpus: 8
    ram: 8192
    cpu_topology:
      sockets: 1
      cores: 4
      threads: 2
    numa:
      cell0:
        memory: 8388608
        cpus: 0-7
