##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - system.maas.region.single
  - service.maas.cluster.single
  - cluster.baremetal-mcp-pike-common-ha.infra.lab_proxy_pdf
parameters:
  _param:
    dhcp_interface: ${_param:opnfv_vm_primary_interface}
    primary_interface: ${_param:opnfv_vm_secondary_interface}
    pxe_interface: ${_param:opnfv_vm_tertiary_interface}
    interface_mtu: 1500
    # MaaS has issues using MTU > 1500 for PXE interface
    pxe_interface_mtu: 1500
    linux_system_codename: xenial
    maas_admin_username: opnfv
    maas_admin_password: opnfv_secret
    maas_db_password: opnfv_secret
    dns_server01: ${_param:opnfv_dns_server01}
    single_address: ${_param:infra_maas_node01_deploy_address}
    hwe_kernel: 'ga-16.04'
  maas:
    region:
      salt_master_ip: ${_param:reclass_config_master}
      domain: ${_param:cluster_domain}
      maas_config:
        commissioning_distro_series: 'xenial'
        default_distro_series: 'xenial'
        default_osystem: 'ubuntu'
        default_storage_layout: 'lvm'
        enable_http_proxy: true
        disk_erase_with_secure_erase: false
        dnssec_validation: 'no'
        enable_third_party_drivers: true
        network_discovery: 'enabled'
        default_min_hwe_kernel: ${_param:hwe_kernel}
      subnets:
        opnfv_maas_pxe:
          name: ${_param:opnfv_infra_maas_pxe_network_address}/24
          cidr: ${_param:opnfv_infra_maas_pxe_network_address}/24
          gateway_ip: ${_param:single_address}
          iprange:
            start: ${_param:opnfv_infra_maas_pxe_start_address}
            end: ${_param:opnfv_infra_maas_pxe_end_address}
            type: dynamic
          vlans:
            untagged:
              vid: 0
              dhcp_on: true
              primary_rack: ${_param:infra_maas_node01_hostname}
      machines:
        kvm01:
          interface:
            mac: ${_param:opnfv_maas_node01_interface_mac}
          power_parameters:
            power_address: ${_param:opnfv_maas_node01_power_address}
            power_password: ${_param:opnfv_maas_node01_power_password}
            power_type: ${_param:opnfv_maas_node01_power_type}
            power_user: ${_param:opnfv_maas_node01_power_user}
          architecture: ${_param:opnfv_maas_node01_architecture}
          distro_series: xenial
          hwe_kernel: ${_param:hwe_kernel}
        kvm02:
          interface:
            mac: ${_param:opnfv_maas_node02_interface_mac}
          power_parameters:
            power_address: ${_param:opnfv_maas_node02_power_address}
            power_password: ${_param:opnfv_maas_node02_power_password}
            power_type: ${_param:opnfv_maas_node02_power_type}
            power_user: ${_param:opnfv_maas_node02_power_user}
          architecture: ${_param:opnfv_maas_node02_architecture}
          distro_series: xenial
          hwe_kernel: ${_param:hwe_kernel}
        kvm03:
          interface:
            mac: ${_param:opnfv_maas_node03_interface_mac}
          power_parameters:
            power_address: ${_param:opnfv_maas_node03_power_address}
            power_password: ${_param:opnfv_maas_node03_power_password}
            power_type: ${_param:opnfv_maas_node03_power_type}
            power_user: ${_param:opnfv_maas_node03_power_user}
          architecture: ${_param:opnfv_maas_node03_architecture}
          distro_series: xenial
          hwe_kernel: ${_param:hwe_kernel}
        cmp001:
          interface:
            mac: ${_param:opnfv_maas_node04_interface_mac}
          power_parameters:
            power_address: ${_param:opnfv_maas_node04_power_address}
            power_password: ${_param:opnfv_maas_node04_power_password}
            power_type: ${_param:opnfv_maas_node04_power_type}
            power_user: ${_param:opnfv_maas_node04_power_user}
          architecture: ${_param:opnfv_maas_node04_architecture}
          distro_series: xenial
          hwe_kernel: ${_param:hwe_kernel}
        cmp002:
          interface:
            mac: ${_param:opnfv_maas_node05_interface_mac}
          power_parameters:
            power_address: ${_param:opnfv_maas_node05_power_address}
            power_password: ${_param:opnfv_maas_node05_power_password}
            power_type: ${_param:opnfv_maas_node05_power_type}
            power_user: ${_param:opnfv_maas_node05_power_user}
          architecture: ${_param:opnfv_maas_node05_architecture}
          distro_series: xenial
          hwe_kernel: ${_param:hwe_kernel}
    cluster:
      saltstack_repo_xenial: "http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.11/ xenial main"
  linux:
    network:
      interface:
        dhcp_interface:
          enabled: true
          name: ${_param:dhcp_interface}
          type: eth
          proto: dhcp
        primary_interface:
          enabled: true
          name: ${_param:primary_interface}
          mtu: ${_param:interface_mtu}
          proto: static
          address: ${_param:infra_maas_node01_address}
          netmask: 255.255.255.0
          type: eth
        pxe_interface:
          enabled: true
          name: ${_param:pxe_interface}
          mtu: ${_param:pxe_interface_mtu}
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
          type: eth
