---
classes:
  - system.reclass.storage.system.opendaylight_control_single
  - cluster.baremetal-mcp-ocata-odl-ha.infra
  - cluster.baremetal-mcp-ocata-common.infra.config
parameters:
  reclass:
    storage:
      node:
        opendaylight_control_node01:
          classes:
            - cluster.${_param:cluster_name}.opendaylight.control
          params:
            linux_system_codename: xenial
            single_address: ${_param:opendaylight_server_node01_single_address}
