##############################################################################
# Copyright (c) 2018 Linux Foundation, Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
### LF POD 2 installer descriptor file ###

idf:
  version: 0.1
  net_config:
    # NOTE: Network names are likely to change after the PDF spec is updated
    oob:
      interface: 0
      ip-range: 172.30.8.65-172.30.8.75
      vlan: 410
    admin:
      interface: 0
      vlan: native
      network: 192.168.11.0  # Untagged, 'PXE/Admin' on wiki, different IP
      mask: 24
    mgmt:
      interface: 0
      vlan: 300
      network: 10.167.4.0    # Tagged, 'vlan 300' on wiki
      mask: 24
    storage:
      interface: 3
      vlan: 301
      network: 10.2.0.0      # Tagged, not the same with 'storage' on wiki
      mask: 24
    private:
      interface: 1
      vlan: 1000
      network: 10.1.0.0      # Tagged, not the same with 'private' on wiki
      mask: 24
    public:
      interface: 2
      vlan: native
      network: 172.30.10.0   # Untagged, 'public' on wiki
      mask: 24
      gateway: 172.30.10.1
      dns:
        - 8.8.8.8
        - 8.8.4.4
  fuel:
    jumphost:
      bridges:
        admin: 'pxebr'
        mgmt: 'br-ctl'
        private: ~
        public: ~
    network:
      node:
        # Ordered-list, index should be in sync with node index in PDF
        - interfaces: &interfaces
            # Ordered-list, index should be in sync with interface index in PDF
            - 'enp6s0'
            - 'enp7s0'
            - 'enp8s0'
            - 'enp9s0'
          busaddr: &busaddr
            # Bus-info reported by `ethtool -i ethX`
            - '0000:06:00.0'
            - '0000:07:00.0'
            - '0000:08:00.0'
            - '0000:09:00.0'
        - interfaces: *interfaces
          busaddr: *busaddr
        - interfaces: *interfaces
          busaddr: *busaddr
        - interfaces: *interfaces
          busaddr: *busaddr
        - interfaces: *interfaces
          busaddr: *busaddr
