##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
### LF POD 2 installer descriptor file ###

idf:
  version: 0.1
  fuel:
    jumphost:
      bridges:
        admin: 'pxebr'
        mgmt: 'br-ctl'
        private: ''
        public: ''
    network:
      node:
        # Ordered-list, index should be in sync with node index in PDF
        - interfaces: &interfaces
            # Ordered-list, index should be in sync with interface index in PDF
            - 'enp6s0'
            - 'enp7s0'
            - 'enp8s0'
            - 'enp9s0'
          busaddr: &busaddr
            # Bus-info reported by `ethtool -i ethX`
            - '0000:06:00.0'
            - '0000:07:00.0'
            - '0000:08:00.0'
            - '0000:09:00.0'
        - interfaces: *interfaces
          busaddr: *busaddr
        - interfaces: *interfaces
          busaddr: *busaddr
        - interfaces: *interfaces
          busaddr: *busaddr
        - interfaces: *interfaces
          busaddr: *busaddr
