##############################################################################
# Copyright (c) 2018 Linux Foundation, Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
### LF POD 2 descriptor file ###

version: 1.0
details:
  pod_owner: Trevor Bramwell
  contact: tbramwell@linuxfoundation.org
  lab: LF Pharos Lab
  location: Portland
  type: production
  link: https://wiki.opnfv.org/display/pharos/LF+POD+2
##############################################################################
jumphost:
  name: pod2-jump
  node:
    type: baremetal
    vendor: Cisco Systems Inc
    model: UCSB-B200-M4
    arch: x86_64
    cpus: 2
    cpu_cflags: haswell
    cores: 8
    memory: 128G
  disks: &disks
    - name: 'disk1'
      disk_capacity: 2400G
      disk_type: hdd
      disk_interface: sas
      disk_rotation: 0
  os: centos-7
  remote_params: &remote_params
    type: ipmi
    versions:
      - 2.0
    user: admin
    pass: octopus
  remote_management:
    <<: *remote_params
    address: 172.30.8.83
    mac_address: "a8:9d:21:c9:c4:9e"
  interfaces:
    - mac_address: "00:25:b5:a0:00:1a"
      speed: 40gb
      features: 'dpdk|sriov'
      address: 192.168.11.1
      name: 'nic1'
    - mac_address: "00:25:b5:a0:00:1b"
      speed: 40gb
      features: 'dpdk|sriov'
      name: 'nic2'
    - mac_address: "00:25:b5:a0:00:1c"
      speed: 40gb
      features: 'dpdk|sriov'
      name: 'nic3'
    - mac_address: "00:25:b5:a0:00:1d"
      speed: 40gb
      features: 'dpdk|sriov'
      name: 'nic4'
##############################################################################
nodes:
  - name: pod2-node1
    node: &nodeparams
      type: baremetal
      vendor: Cisco Systems Inc
      model: UCSB-B200-M4
      arch: x86_64
      cpus: 2
      cpu_cflags: haswell
      cores: 8
      memory: 32G
    disks: *disks
    remote_management:
      <<: *remote_params
      address: 172.30.8.75
      mac_address: "a8:9d:21:c9:8b:56"
    interfaces:
      - mac_address: "00:25:b5:a0:00:2a"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic1'
      - mac_address: "00:25:b5:a0:00:2b"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic2'
      - mac_address: "00:25:b5:a0:00:2c"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic3'
      - mac_address: "00:25:b5:a0:00:2d"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic4'
  ############################################################################
  - name: pod2-node2
    node: *nodeparams
    disks: *disks
    remote_management:
      <<: *remote_params
      address: 172.30.8.65
      mac_address: "a8:9d:21:c9:4d:26"
    interfaces:
      - mac_address: "00:25:b5:a0:00:3a"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic1'
      - mac_address: "00:25:b5:a0:00:3b"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic2'
      - mac_address: "00:25:b5:a0:00:3c"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic3'
      - mac_address: "00:25:b5:a0:00:3d"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic4'
  ############################################################################
  - name: pod2-node3
    node: *nodeparams
    disks: *disks
    remote_management:
      <<: *remote_params
      address: 172.30.8.74
      mac_address: "a8:9d:21:c9:3a:92"
    interfaces:
      - mac_address: "00:25:b5:a0:00:4a"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic1'
      - mac_address: "00:25:b5:a0:00:4b"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic2'
      - mac_address: "00:25:b5:a0:00:4c"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic3'
      - mac_address: "00:25:b5:a0:00:4d"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic4'
  ############################################################################
  - name: pod2-node4
    node: *nodeparams
    disks: *disks
    remote_management:
      <<: *remote_params
      address: 172.30.8.73
      mac_address: "74:a2:e6:a4:14:9c"
    interfaces:
      - mac_address: "00:25:b5:a0:00:5a"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic1'
      - mac_address: "00:25:b5:a0:00:5b"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic2'
      - mac_address: "00:25:b5:a0:00:5c"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic3'
      - mac_address: "00:25:b5:a0:00:5d"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic4'
  ############################################################################
  - name: pod2-node5
    node: *nodeparams
    disks: *disks
    remote_management:
      <<: *remote_params
      address: 172.30.8.72
      mac_address: "a8:9d:21:a0:15:9c"
    interfaces:
      - mac_address: "00:25:b5:a0:00:6a"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic1'
      - mac_address: "00:25:b5:a0:00:6b"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic2'
      - mac_address: "00:25:b5:a0:00:6c"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic3'
      - mac_address: "00:25:b5:a0:00:6d"
        speed: 40gb
        features: 'dpdk|sriov'
        name: 'nic4'
