##############################################################################
# Copyright (c) 2018 Ericsson AB, Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
### Fuel@OPNFV sample VIRTUAL POD descriptor file ###
### NOTE: This is subject to change as vPDF is not yet officialy supported ###

version: 0.0  # Intentionally invalid to indicate this is experimental
details:
  pod_owner: Fuel@OPNFV
  contact: Fuel@OPNFV
  lab: Example Lab
  location: Example Location
  type: development
  link: https://wiki.opnfv.org/display/pharos/
##############################################################################
jumphost:
  name: virtual1-jump
  node:
    type: baremetal
    vendor: HP
    model: ProLiant BL460c Gen8
    arch: x86_64
    cpus: 2
    cpu_cflags: ivybridge
    cores: 10
    memory: 64G
  disks:
    - name: 'disk1'
      disk_capacity: 800G
      disk_type: hdd
      disk_interface: scsi
      disk_rotation: 15000
  os: ubuntu-16.04
  remote_management:
    type: ipmi
    versions:
      - 1.0
      - 2.0
    user: changeme
    pass: changeme
    address: 0.0.0.0
    mac_address: "00:00:00:00:00:00"
  interfaces:
    - name: 'nic1'
      speed: 10gb
      features: 'dpdk|sriov'
      mac_address: "00:00:00:00:00:00"
      vlan: native
    - name: 'nic2'
      speed: 10gb
      features: 'dpdk|sriov'
      mac_address: "00:00:00:00:00:00"
      vlan: native
##############################################################################
nodes:
  - name: node-1  # noha ctl01 or ha (novcp) kvm01
    node: &nodeparams
      # Fuel overrides certain params (e.g. cpus, mem) based on node role later
      type: virtual
      vendor: libvirt
      model: virt
      arch: x86_64
      cpus: 1
      cpu_cflags: ivybridge
      cores: 8
      memory: 6G
    disks: &disks
      - name: 'disk1'
        disk_capacity: 100G
        disk_type: hdd
        disk_interface: scsi  # virtio-scsi
        disk_rotation: 15000
    remote_management: &remotemgmt
      type: libvirt
      user: changeme
      pass: changeme
      address: 127.0.0.1  # Not used currently, will be 'qemu:///system' later
    interfaces: &interfaces
      - name: 'nic1'
        speed: 10gb
        features: 'dpdk|sriov'
        mac_address: "00:00:00:00:00:00"  # MACs will be assigned by libvirt
        vlan: native
      - name: 'nic2'
        speed: 10gb
        features: 'dpdk|sriov'
        mac_address: "00:00:00:00:00:00"
        vlan: native
      - name: 'nic3'
        speed: 10gb
        features: 'dpdk|sriov'
        mac_address: "00:00:00:00:00:00"
        vlan: native
      - name: 'nic4'
        speed: 10gb
        features: 'dpdk|sriov'
        mac_address: "00:00:00:00:00:00"
        vlan: native
  ############################################################################
  - name: node-2  # noha gtw01 or ha (novcp) kvm02
    node: *nodeparams
    disks: *disks
    remote_management: *remotemgmt
    interfaces: *interfaces
  ############################################################################
  - name: node-3  # noha odl01 / unused or ha (novcp) kvm02
    node: *nodeparams
    disks: *disks
    remote_management: *remotemgmt
    interfaces: *interfaces
  ############################################################################
  - name: node-4  # cmp001
    node: *nodeparams
    disks: *disks
    remote_management: *remotemgmt
    interfaces: *interfaces
  ############################################################################
  - name: node-5  # cmp002
    node: *nodeparams
    disks: *disks
    remote_management: *remotemgmt
    interfaces: *interfaces
