##############################################################################
# Copyright (c) 2019 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - system.salt.minion.cert.k8s_server_single
  - system.reclass.storage.system.kubernetes_control_single
  - cluster.mcp-common-noha.infra.config
  - cluster.mcp-ovs-noha
  - cluster.all-mcp-arch-common.infra.config_pdf
parameters:
  reclass:
    storage:
      node:
        kubernetes_control01:
          expression: <<node_hostname>>__equals__ctl01
          cluster_param:
            kubernetes_control_node01_address:
              value_template: <<node_control_ip>>
            kubernetes_control_node01_deploy_address:
              value_template: <<node_deploy_ip>>
        kubernetes_compute:
          expression: <<node_hostname>>__startswith__cmp
          node_class:
            value_template:
              - cluster.<<node_cluster>>.kubernetes.compute
          node_param:
            deploy_address:
              value_template: <<node_deploy_ip>>
