##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
parameters:
  _param:
    cluster_domain: ${_param:cluster_name}.local
  linux:
    system:
      apt:
        config:
          prefer_ipv4:
            Acquire::ForceIPv4: true
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
            - cfg01
            - cfg01.${_param:cluster_domain}
        cfg:
          address: ${_param:infra_config_address}
          names:
            - cfg
            - cfg.${_param:cluster_domain}
