##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - system.maas.region.single
  - service.maas.cluster.single
  - cluster.mcp-common-ha.include.lab_proxy_pdf
  - cluster.mcp-common-ha.infra.maas_pdf
parameters:
  _param:
    dhcp_interface: ${_param:opnfv_fn_vm_primary_interface}
    primary_interface: ${_param:opnfv_fn_vm_secondary_interface}
    pxe_interface: ${_param:opnfv_fn_vm_tertiary_interface}
    interface_mtu: 1500
    # MaaS has issues using MTU > 1500 for PXE interface
    pxe_interface_mtu: 1500
    linux_system_codename: xenial
    maas_admin_username: opnfv
    maas_admin_password: opnfv_secret
    maas_db_password: opnfv_secret
    dns_server01: ${_param:opnfv_dns_server01}
    single_address: ${_param:infra_maas_node01_deploy_address}
    hwe_kernel: 'hwe-16.04'
  maas:
    region:
      salt_master_ip: ${_param:reclass_config_master}
      domain: ${_param:cluster_domain}
      maas_config:
        commissioning_distro_series: 'xenial'
        default_distro_series: 'xenial'
        default_osystem: 'ubuntu'
        default_storage_layout: 'lvm'
        enable_http_proxy: true
        disk_erase_with_secure_erase: false
        dnssec_validation: 'no'
        enable_third_party_drivers: true
        network_discovery: 'enabled'
        default_min_hwe_kernel: ${_param:hwe_kernel}
    cluster:
      saltstack_repo_xenial: "http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2016.11/ xenial main"
  linux:
    network:
      interface:
        dhcp_interface:
          enabled: true
          name: ${_param:dhcp_interface}
          type: eth
          proto: dhcp
        primary_interface:
          enabled: true
          name: ${_param:primary_interface}
          mtu: ${_param:interface_mtu}
          proto: static
          address: ${_param:infra_maas_node01_address}
          netmask: 255.255.255.0
          type: eth
        pxe_interface:
          enabled: true
          name: ${_param:pxe_interface}
          mtu: ${_param:pxe_interface_mtu}
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
          type: eth
