dha-pod-config-metadata:
  title: Deployment Hardware Adapter (DHA) for fuel development pipeline - Ericsson ELX version
  version: 0.0.3
  created: Feb 2 2016
  comment: ELX Fuel8 version

# Adapter to use for this definition
adapter: libvirt

# Node list.
# Mandatory property is id, all other properties are adapter specific.

nodes:
- id: 1
  libvirtName: controller1
  libvirtTemplate: templates/virtual_environment/vms/controller.xml
- id: 2
  libvirtName: compute1
  libvirtTemplate: templates/virtual_environment/vms/compute.xml
- id: 3
  libvirtName: compute2
  libvirtTemplate: templates/virtual_environment/vms/compute.xml
- id: 4
  libvirtName: compute3
  libvirtTemplate: templates/virtual_environment/vms/compute.xml
- id: 5
  libvirtName: fuel-master
  libvirtTemplate: templates/virtual_environment/vms/fuel.xml
  isFuel: yes
  username: root
  password: r00tme

virtNetConfDir: templates/virtual_environment/networks

disks:
  fuel: 100G
  controller: 100G
  compute: 100G

# Here the infrastructure VMs can be defined.
# The entries are not mandatory! If it is left empty
# the default defined in deploy/templates will
# be used.
define_vms:
  fuel:
    vcpu:
      value: 2
    memory:
      attribute_equlas:
        unit: KiB
      value: 8388608
    currentMemory:
      attribute_equlas:
        unit: KiB
      value: 8388608
    devices:
      interface:
        # With attribute_equlas someone can define which
        # interface type is meant
        attribute_equlas:
          type: network
        # This will overwrite the type of the model of
        # the interface
        model:
          attribute:
            type: e1000
  controller:
    devices:
      interface:
        attribute_equlas:
          type: network
        model:
          attribute:
            type: e1000
  compute:
    devices:
      interface:
        attribute_equlas:
          type: network
        model:
          attribute:
            type: e1000

