#!/bin/bash -e
##############################################################################
# Copyright (c) 2019 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x

# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/../../scripts/lib.sh"

#IEC_REPO_URI='https://gerrit.akraino.org/r/iec'
IEC_REPO_URI='https://github.com/alexandruavadanii/iec'
IEC_USER='ubuntu'
# shellcheck disable=SC2016
IEC_REPO_PATH=$(su - "${IEC_USER}" -c 'echo ${HOME}/iec')

POD_NETWORK_CIDR='100.100.0.0/16' # Avoid overlapping Fuel's PXE/admin net

[ -e "${IEC_REPO_PATH}" ] || su - "${IEC_USER}" -c \
  "git clone '${IEC_REPO_URI}' '${IEC_REPO_PATH}'"
wait_for 3.0 "! salt-cp 'iec*' -C '${IEC_REPO_PATH}/scripts/' \
                                  '${IEC_REPO_PATH}/' | grep -e False"
salt -C 'iec*' cmd.run "chown -R ${IEC_USER}:${IEC_USER} ${IEC_REPO_PATH}"

salt -C 'iec*' cmd.run runas="${IEC_USER}" "${IEC_REPO_PATH}/scripts/k8s_common.sh"

IEC_MASTER_IP=$(salt --out txt -C 'iec* and *01*' pillar.get \
                _param:single_address | cut -d ' ' -f2)
salt -C 'iec* and *01*' cmd.run runas="${IEC_USER}" \
  "${IEC_REPO_PATH}/scripts/k8s_master.sh ${IEC_MASTER_IP} ${POD_NETWORK_CIDR}"

KUBE_NODE_CNT=$(salt --out txt -C 'iec* and *01*' cmd.run runas="${IEC_USER}" \
                'kubectl get nodes | grep -c -e "^iec"' | cut -d ' ' -f2)
if [ "${KUBE_NODE_CNT}" != "$(salt-key | grep -c -e '^iec')" ]; then
  KUBE_JOIN_CMD=$(salt --out txt -C 'iec* and *01*' cmd.run runas="${IEC_USER}" \
                  'kubeadm token create --print-join-command' | cut -d ' ' -f2-)
  salt -C 'iec* and not *01*' cmd.run "${KUBE_JOIN_CMD}"
fi
salt -C 'iec* and *01*' cmd.run runas="${IEC_USER}" 'kubectl get nodes'

salt -C 'iec* and *01*' cmd.run runas="${IEC_USER}" "${IEC_REPO_PATH}/scripts/cni/calico/calico.sh"
salt -C 'iec* and *01*' cmd.run runas="${IEC_USER}" "${IEC_REPO_PATH}/scripts/nginx.sh"
salt -C 'iec* and *01*' cmd.run runas="${IEC_USER}" "${IEC_REPO_PATH}/scripts/helm.sh"
