#!/bin/bash -e
##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x

# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/../../scripts/lib.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../../scripts/xdf_data.sh"

cluster_nodes_query="${control_nodes_query} or cmp*"

# KVM, compute node prereqs
# patch the networking module for Debian based distros
debian_ip_source=/usr/lib/python2.7/dist-packages/salt/modules/debian_ip.py
salt -C "${cluster_nodes_query}" file.line $debian_ip_source \
  content='iface = iface.lower()' mode='delete'

salt -C "${cluster_nodes_query}" file.replace $debian_ip_source \
  pattern="^\s{8}__salt__\['pkg.install'\]\('vlan'\)" \
  repl="\n        if not __salt__['pkg.version']('vlan'):\n            __salt__['pkg.install']('vlan')"

salt -C "${cluster_nodes_query}" state.apply linux.system.repo
salt -C "${cluster_nodes_query}" pkg.install force_yes=true bridge-utils,python-jinja2
salt -C "${cluster_nodes_query}" service.restart salt-minion
wait_for 5.0 "salt -C '${cluster_nodes_query}' state.apply salt.minion"
salt -C "${cluster_nodes_query}" file.remove /etc/resolv.conf
salt -C "${cluster_nodes_query}" file.touch /etc/resolv.conf
wait_for 5.0 "salt -C '${cluster_nodes_query}' state.apply linux,ntp"
wait_for 30.0 "salt -C '${cluster_nodes_query}' test.ping"

salt -C "${cluster_nodes_query}" cmd.run 'reboot'
wait_for 90.0 "salt -C '${cluster_nodes_query}' test.ping"

salt -C "${cluster_nodes_query}" state.apply linux,ntp
salt -C "${cluster_nodes_query}" pkg.upgrade refresh=False dist_upgrade=True
