#!/bin/bash -e
##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x

# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/../../scripts/lib.sh"

# KVM, compute node prereqs
# patch the networking module for Debian based distros
debian_ip_source=/usr/lib/python2.7/dist-packages/salt/modules/debian_ip.py
salt -C 'kvm* or cmp*' file.line $debian_ip_source \
  content='iface = iface.lower()' mode='delete'

salt -C 'kvm* or cmp*' file.replace $debian_ip_source \
  pattern="^\s{8}__salt__\['pkg.install'\]\('vlan'\)" \
  repl="\n        if not __salt__['pkg.version']('vlan'):\n            __salt__['pkg.install']('vlan')"

salt -C 'kvm*' pkg.install bridge-utils
salt -C 'kvm*' state.apply linux.network,linux.system.kernel
salt -C 'kvm* or cmp*' state.apply salt.minion
salt -C 'cmp*' state.apply linux.system
salt -C 'cmp*' state.apply linux.network || true

# disable dhcp offered routes on compute nodes
salt -C 'cmp*' file.write /etc/dhcp/dhclient-enter-hooks.d/no-default-route \
  args='unset new_routers'

salt -C 'kvm* or cmp*' system.reboot
wait_for 90.0 "salt -C 'kvm* or cmp*' test.ping"

salt -C 'kvm* or cmp*' state.apply linux,ntp
salt -C 'kvm* or cmp*' pkg.upgrade refresh=False
