#!/bin/bash -e
##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x

# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/../../scripts/lib.sh"

salt -I 'nova:compute' system.reboot
wait_for 90 "! salt -I 'nova:compute' test.ping | " \
  "tee /dev/stderr | grep -Fq 'Not connected'"
salt -I 'nova:compute' state.sls linux.network

# switch to UCA repos since fuel-infra packages have bugs
salt -I 'nova:compute' cmd.run 'rm -vrf /etc/apt/preferences.d/*'
salt -I 'nova:compute' file.remove '/etc/apt/sources.list.d/mirantis_openstack.list'
salt -I 'nova:compute' pkg.refresh_db

salt -I 'nova:compute' pkg.install libvirt-bin
salt -I 'nova:compute' file.chown /var/run/openvswitch libvirt-qemu kvm
