#!/bin/bash -e
##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x
DEPLOY_TYPE=${DEPLOY_TYPE:-virtual}
NODE_MASK='*'

[ "${DEPLOY_TYPE}" = 'virtual' ] || NODE_MASK='mas01*'

# Initialization specific to VMs on FN (all for virtual, cfg|mas for baremetal)
salt -C "${NODE_MASK} or cfg01*" saltutil.sync_all
salt -C "${NODE_MASK} or cfg01*" state.apply salt | \
  grep -Fq 'No response' && salt "${NODE_MASK} or cfg01*" state.apply salt

salt -C 'I@salt:master' state.sls linux
salt -C "${NODE_MASK} and not cfg01*" state.sls linux || true
salt -C "${NODE_MASK} and not cfg01*" pkg.upgrade refresh=False

salt -C "${NODE_MASK} or cfg01*" state.sls ntp
