#!/bin/bash -e
##############################################################################
# Copyright (c) 2019 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

# Install etcd
salt -I 'etcd:server' state.sls etcd.server.service
salt -I 'etcd:server' cmd.run ". /var/lib/etcd/configenv && etcdctl cluster-health"

# Install Kubernetes and Calico
salt -I 'kubernetes:master' state.sls kubernetes.master.kube-addons
salt -I 'kubernetes:pool' state.sls kubernetes.pool
salt -I 'kubernetes:pool' cmd.run "calicoctl node status"
salt -I 'kubernetes:pool' cmd.run "calicoctl get ippool"

# Setup NAT for Calico
salt -I 'kubernetes:master' state.sls etcd.server.setup

# Run whole master to check consistency
salt -I 'kubernetes:master' state.sls kubernetes exclude=kubernetes.master.setup

# Register addons
salt -I 'kubernetes:master' state.sls kubernetes.master.setup
