#!/bin/bash -e
##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x

# Determine public network based on external IPs from compute node
PUBLIC_NET_CIDR=$(salt -C 'I@nova:compute and *01*' \
  pillar.get _param:opnfv_net_public --out yaml | cut -d' ' -f2 )
PUBLIC_NET_GATEWAY=$(salt -C 'I@nova:compute and *01*' \
  pillar.get _param:opnfv_net_public_gw --out yaml | cut -d' ' -f2 )

# Default values
[ -n "${PUBLIC_NET_CIDR}" ] PUBLIC_NET="10.16.0.0/24"
[ -n "${PUBLIC_NET_GATEWAY}" ] PUBLIC_NET_GATEWAY="10.16.0.1"

# Split CIDR
PUBLIC_NET=$(echo $PUBLIC_NET_CIDR | cut -d'/' -f1)
PUBLIC_NET_MASK=$(echo $PUBLIC_NET_CIDR | cut -d'/' -f2)

# Define public pool
# - Supported pool ranges:
# /27	max end 30. Only if pool size set to 10
# /26 max end 62
# /25 max end 126
# /24 max end 254
POOL_SIZE=40
POOL_START=20
POOL_START_IP="${PUBLIC_NET%.*}.$POOL_START"
POOL_END_IP="${PUBLIC_NET%.*}.$(($POOL_START+$POOL_SIZE))"

# Print openstack status and setup network
salt -C 'I@nova:controller and *01*' cmd.run ". /root/keystonercv3; \
  openstack compute service list; \
  openstack network agent list; \
  openstack stack list; \
  openstack volume service list"
salt -C 'I@nova:controller and *01*' cmd.run ". /root/keystonercv3; \
  openstack network create --external --default --provider-network-type flat \
    --provider-physical-network physnet1 floating_net"
salt -C 'I@nova:controller and *01*' cmd.run ". /root/keystonercv3; \
  openstack subnet create --subnet-range ${PUBLIC_NET} --gateway ${PUBLIC_NET_GATEWAY} \
    --allocation-pool start=${POOL_START_IP},end=${POOL_END_IP} \
    --no-dhcp --network floating_net floating_subnet"
