#!/bin/bash -e
##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x

# Determine public network based on external IPs from compute node
PUBLIC_NET=$(salt -C 'I@nova:compute and *01*' \
  pillar.get _param:opnfv_net_public --out yaml | cut -d' ' -f2 )
PUBLIC_NET_GATEWAY=$(salt -C 'I@nova:compute and *01*' \
  pillar.get _param:opnfv_net_public_gw --out yaml | cut -d' ' -f2 )
POOL_START_IP=$(salt -C 'I@nova:compute and *01*' \
pillar.get _param:opnfv_net_public_pool_start --out yaml | cut -d' ' -f2 )
POOL_END_IP=$(salt -C 'I@nova:compute and *01*' \
  pillar.get _param:opnfv_net_public_pool_end --out yaml | cut -d' ' -f2 )

# Default values
PUBLIC_NET="${PUBLIC_NET:-10.16.0.0/24}"
PUBLIC_NET_GATEWAY="${PUBLIC_NET_GATEWAY:-10.16.0.1}"
POOL_START_IP="${POOL_START_IP:-10.16.0.130}"
POOL_END_IP="${POOL_END_IP:-10.16.0.254}"

# Print openstack status and setup network
salt -C 'I@nova:controller and *01*' cmd.run ". /root/keystonercv3; \
  openstack compute service list; \
  openstack network agent list; \
  openstack stack list; \
  openstack volume service list"
salt -C 'I@nova:controller and *01*' cmd.run ". /root/keystonercv3; \
  openstack network create --external --default --provider-network-type flat \
  --provider-physical-network physnet1 floating_net"
salt -C 'I@nova:controller and *01*' cmd.run ". /root/keystonercv3; \
  openstack subnet create --gateway ${PUBLIC_NET_GATEWAY} --no-dhcp \
  --allocation-pool start=${POOL_START_IP},end=${POOL_END_IP} \
  --network floating_net --subnet-range ${PUBLIC_NET} floating_subnet"
