#!/bin/bash -e
##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x

salt -I 'neutron:gateway' state.sls neutron
# FIXME: Temporary workaround for py3 compat
salt -C 'gtw*' file.patch /usr/share/vpp/api/core/interface.api.json /var/tmp/vpp.patch || true
salt -C 'gtw*' service.restart vpp-agent
