#!/bin/bash -e
##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x

salt -I 'neutron:gateway' state.sls neutron

# FIXME: Temporary workaround for VPP 20.01 compat
salt -C 'gtw*' cmd.run 'cd /usr/lib/python3/dist-packages/ && patch -p1 < /var/tmp/vpp.patch'
salt -C 'gtw*' service.restart vpp-agent
