#!/bin/bash -e
##############################################################################
# Copyright (c) 2019 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

salt -I 'nova:compute' pkg.install python-nova
# https://bugs.launchpad.net/nova/+bug/1809123
salt -I 'nova:compute' file.replace /usr/lib/python2.7/dist-packages/nova/privsep/path.py \
  pattern="^\s{4}os\.utime\(path, None\)" \
  repl="\n    with open(path, 'a'):\n        os.utime(path, None)"
