#!/bin/bash -e
##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB, Tieto and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
# Deploy ONAP on top of OPNFV installed by Fuel/MCP
# ONAP installation is managed by OPNFV Auto project

AUTO_INSTALL_DIR=$HOME/auto
AUTO_REPO="https://gerrit.opnfv.org/gerrit/auto"
ONAP_INSTALL_SCRIPT="ci/deploy-onap-fuel.sh"

# clone auto repository
git clone $AUTO_REPO $AUTO_INSTALL_DIR

# TEMPORARY download of ONAP installation script on review
wget "https://gerrit.opnfv.org/gerrit/gitweb?p=auto.git;a=blob_plain;f=ci/deploy-onap-fuel.sh;hb=refs/changes/71/64371/2" -O ${AUTO_INSTALL_DIR}/${ONAP_INSTALL_SCRIPT}
chmod a+x ${AUTO_INSTALL_DIR}/${ONAP_INSTALL_SCRIPT}

# execute ONAP installation script
cd $AUTO_INSTALL_DIR
export $AUTO_INSTALL_DIR
sudo -E $ONAP_INSTALL_SCRIPT
