#!/bin/bash -e
##############################################################################
# Copyright (c) 2017 Mirantis Inc., Enea AB, Tieto and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
# Deploy ONAP on top of OPNFV installed by Fuel/MCP
# ONAP installation is managed by OPNFV Auto project

INSTALL_DIR=$HOME/auto
AUTO_REPO="https://gerrit.opnfv.org/gerrit/auto"
ONAP_INSTALL_SCRIPT="ci/deploy-onap-fuel.sh"

# clone auto repository
git clone $AUTO_REPO $INSTALL_DIR

# execute ONAP installation script
cd $INSTALL_DIR
sudo $ONAP_INSTALL_SCRIPT
