#!/bin/bash -e
##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

pkg_base='http://ubuntu-cloud.archive.canonical.com/ubuntu/pool/main/s/sqlalchemy'
pkgs='python-sqlalchemy-ext_1.2.8+ds1-1ubuntu2~cloud0_amd64.deb python-sqlalchemy_1.2.8+ds1-1ubuntu2~cloud0_all.deb'

for pkg in $pkgs; do
  salt -I 'neutron:server' cmd.run "wget -P /tmp -N $pkg_base/$pkg && dpkg --force-all -i /tmp/$pkg"
done

salt -I 'neutron:server' service.restart neutron-server
