#!/bin/bash -e
##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

sqlalchemy_ver=1.2.1

salt -I 'neutron:server' pkg.install python-pip
salt -I 'neutron:server' cmd.run \
  "sudo -H -u neutron pip install --user SQLAlchemy==${sqlalchemy_ver}"

salt -I 'neutron:server' service.restart neutron-server
