#!/bin/bash -e
# shellcheck disable=SC1090
##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x

# shellcheck disable=SC1090
source "$(dirname "${BASH_SOURCE[0]}")/../../scripts/lib.sh"
source "$(dirname "${BASH_SOURCE[0]}")/../../scripts/xdf_data.sh"

CI_DEBUG=${CI_DEBUG:-0}; [[ "${CI_DEBUG}" =~ (false|0) ]] || set -x
# shellcheck disable=SC2154,SC2086,SC2116
LOCAL_VIRT_NODES=$(echo ${virtual_nodes[*]}) # unquoted to filter space
[[ ! "${LOCAL_VIRT_NODES}" =~ mas01 ]] || LOCAL_VIRT_NODES='mas01'
NODE_MASK="${LOCAL_VIRT_NODES// /|}"

wait_for 5.0 "salt-call state.sls reclass,linux.network,salt.minion \
              exclude='[{id: reclass_packages}, {id: /etc/reclass/reclass-config.yml}]'"
# Workaround for: https://github.com/salt-formulas/reclass/issues/77
salt-call file.replace '/usr/local/lib/python2.7/dist-packages/reclass/settings.py' \
  pattern='(ignore_overwritten_missing_references)defaults.' repl='\1'
wait_for 3.0 "salt -C 'E@^(${NODE_MASK}).*' saltutil.refresh_pillar"

# NOTE: domain name changes are not yet supported without a clean redeploy

# Init specific to VMs on FN (all for virtual, mas for baremetal)
wait_for 3.0 "(for n in ${LOCAL_VIRT_NODES}; do salt -C \${n}.* test.ping || exit; done)"

wait_for 3.0 "salt -C 'E@^(${NODE_MASK}).*' state.sls linux.system,linux.storage"
wait_for 2.0 "salt -C 'E@^(${NODE_MASK}).*' state.sls linux.network"
salt -C "E@^(${NODE_MASK}).*" system.reboot
wait_for 90.0 "salt -C 'E@^(${NODE_MASK}).*' test.ping"
wait_for 3.0 "salt -C 'E@^(${NODE_MASK}).*' pkg.upgrade refresh=False dist_upgrade=True"
wait_for 3.0 "salt -C 'E@^(${NODE_MASK}).*' saltutil.sync_all"
wait_for 3.0 "salt -C 'E@^(${NODE_MASK}).*' state.apply salt"

wait_for 3.0 "salt -C 'E@^(${NODE_MASK}).*' state.sls ntp"
