##############################################################################
# Copyright (c) 2019 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - cluster.mcp-common-noha.infra.config
  - cluster.mcp-iec-noha
  - cluster.all-mcp-arch-common.infra.config_pdf
parameters:
  _param:
    akraino_iec_node01_hostname: iec01
    akraino_iec_node02_hostname: iec02
    akraino_iec_node03_hostname: iec03
  reclass:
    storage:
      ~node:
        akraino_iec_node01:
          name: ${_param:akraino_iec_node01_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.akraino.iec
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: ${_param:linux_system_codename}
            single_address: ${_param:opnfv_openstack_control_node01_address}
            pxe_admin_address: ${_param:opnfv_openstack_control_node01_pxe_admin_address}
        akraino_iec_node02:
          name: ${_param:akraino_iec_node02_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.akraino.iec
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: ${_param:linux_system_codename}
            single_address: ${_param:opnfv_openstack_control_node02_address}
            pxe_admin_address: ${_param:opnfv_openstack_control_node02_pxe_admin_address}
        akraino_iec_node03:
          name: ${_param:akraino_iec_node03_hostname}
          domain: ${_param:cluster_domain}
          classes:
          - cluster.${_param:cluster_name}.akraino.iec
          params:
            salt_master_host: ${_param:reclass_config_master}
            linux_system_codename: ${_param:linux_system_codename}
            single_address: ${_param:opnfv_openstack_control_node03_address}
            pxe_admin_address: ${_param:opnfv_openstack_control_node03_pxe_admin_address}
