##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
<<<<<<< HEAD:mcp/reclass/classes/cluster/mcp-odl-ha/openstack/database.yml
  - cluster.mcp-common-ha.openstack_interface_vcp_biport
  - cluster.mcp-common-ha.openstack_database
  - cluster.mcp-odl-ha.infra.init_vcp
=======
  - cluster.mcp-pike-common-ha.openstack_interface_vcp_biport
  - cluster.mcp-pike-common-ha.openstack_database
  - cluster.mcp-pike-ovn-ha.infra.init_vcp
>>>>>>> [ha] Add OVN scenario:mcp/reclass/classes/cluster/mcp-pike-ovn-ha/openstack/database.yml
