##############################################################################
# Copyright (c) 2015 Ericsson AB and others.
# stefan.k.berg@ericsson.com
# jonas.bjurel@ericsson.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

############################################################################### # Description:
# This .yaml configuration file defines the configuration of the fuel
# deployment and is passed as an argument to deploy.sh
# eg. deploy.sh -c https://artifact.opnfv.org/fuel/config
# This will make build.sh fetch this configuration file and configure the
# deployment accordingly.
# After the deployment, a copy of this file gets uploaded to fuel:
# /root/deploy-config.yaml, as well as the sha-1 sum of this file:
# /root/deploy-config.sha1
##############################################################################

##############################################################################
# deployment configuration meta-data
deployment:
   name: myOCL deployment
   version: 0.0.1
   deployment-description: fuel-ocl

##############################################################################
# Base URI's to the actual config files defined further down in this file
# Note that it is a good security practice not to have these base-URIs
# publically available.
resources:
   base-config-base-uri: https://internal.ericsson_opnfv.ca/config
   module-config-base-uri: https://internal.ericsson_opnfv.ca/config

##############################################################################
# The stack-config comprises the dha.yaml and the dea.yaml which contains the
# basic hardware- and OpenStack environment configuration.
# deply.sh will copy:
# <base-config-base-uri>/<dha-config-name>_<dha_config-version>.yaml to local dha.yaml and
# <base-config-base-uri>/<dea-config-name>_<dea_config-version>.yaml to local dea.yaml
stack-config:
   dea-config-name: dea_mtrl
   dea-config-version: 0.0.1
   dha-config-name: dha_mtrl
   dha-config-version: 0.0.1

##############################################################################
# Stack extentions are opnfv added value features in form of a fuel-plugin
# plug-ins listed below will be enabled and configured according to the
# <module-config-base-uri>/<module-config-name>_<module-config-version>.yaml
# It does so by copying the config file to the local plugin config directory
stack-extensions:
   - module: ocl
     module-config-name: ocl
     module-config-version: 0.0.1

##############################################################################
# By editing the override-config section below, you can override arbitrary
# configuration name-space settings
override-config:
fuel:
  FUEL_ACCESS:
    password: myContrail
    user: secret

  NTP1: 10.118.32.193
  NTP2: 10.118.34.193
  NTP3: null

settings:
  editable:
    access:
      email:
        value: christopher.price@ericsson.com

##############################################################################
# The verification pipeline may populate the section below with arbitrary
# testing information, which post deploy can be retreived from the fuel master:
# /root/deploy-config.yaml
test: