classes:
- system.linux.system.repo.saltstack.xenial
- system.maas.region.single
- cluster.baremetal-mcp-ocata-ovs-ha.infra
parameters:
  _param:
    dhcp_interface: ens3
    primary_interface: ens4
    pxe_interface: ens5
    external_interface: ens6
    interface_mtu: 1500
    # MaaS has issues using MTU > 1500 for PXE interface
    pxe_interface_mtu: 1500
    linux_system_codename: xenial
    maas_admin_username: opnfv
    maas_admin_password: opnfv_secret
    maas_db_password: opnfv_secret
    dns_server01: 8.8.4.4
    single_address: ${_param:infra_maas_node01_deploy_address}
  maas:
    region:
      salt_master_ip: ${_param:infra_config_deploy_address}
      domain: ${_param:cluster_domain}
      maas_config:
        commissioning_distro_series: 'xenial'
        default_distro_series: 'xenial'
        default_osystem: 'ubuntu'
        default_storage_layout: 'lvm'
        disk_erase_with_secure_erase: false
        dnssec_validation: 'no'
        enable_third_party_drivers: true
        network_discovery: 'enabled'
        default_min_hwe_kernel: 'hwe-16.04'
      subnets:
        opnfv_fuel_maas_pxe:
          name: ${_param:opnfv_fuel_maas_pxe_network}/24
          cidr: ${_param:opnfv_fuel_maas_pxe_network}/24
          gateway_ip: ${_param:single_address}
          iprange:
            start: ${_param:opnfv_fuel_maas_pxe_iprange_start}
            end: ${_param:opnfv_fuel_maas_pxe_iprange_end}
            type: dynamic
          vlans:
            untagged:
              vid: 0
              dhcp_on: true
              primary_rack: ${_param:infra_maas_node01_hostname}
      machines:
        kvm01:
          interface:
            mac: "00:25:b5:a0:00:2a"
          power_parameters:
            power_address: ${_param:opnfv_maas_node01_power_address}
            power_password: ${_param:opnfv_maas_node01_power_password}
            power_type: ${_param:opnfv_maas_node01_power_type}
            power_user: ${_param:opnfv_maas_node01_power_user}
          architecture: ${_param:opnfv_maas_node01_architecture}
          distro_series: xenial
          hwe_kernel: hwe-16.04
        kvm02:
          interface:
            mac: "00:25:b5:a0:00:3a"
          power_parameters:
            power_address: ${_param:opnfv_maas_node02_power_address}
            power_password: ${_param:opnfv_maas_node02_power_password}
            power_type: ${_param:opnfv_maas_node02_power_type}
            power_user: ${_param:opnfv_maas_node02_power_user}
          architecture: ${_param:opnfv_maas_node02_architecture}
          distro_series: xenial
          hwe_kernel: hwe-16.04
        kvm03:
          interface:
            mac: "00:25:b5:a0:00:4a"
          power_parameters:
            power_address: ${_param:opnfv_maas_node03_power_address}
            power_password: ${_param:opnfv_maas_node03_power_password}
            power_type: ${_param:opnfv_maas_node03_power_type}
            power_user: ${_param:opnfv_maas_node03_power_user}
          architecture: ${_param:opnfv_maas_node03_architecture}
          distro_series: xenial
          hwe_kernel: hwe-16.04
        cmp001:
          interface:
            mac: "00:25:b5:a0:00:5a"
          power_parameters:
            power_address: ${_param:opnfv_maas_node04_power_address}
            power_password: ${_param:opnfv_maas_node04_power_password}
            power_type: ${_param:opnfv_maas_node04_power_type}
            power_user: ${_param:opnfv_maas_node04_power_user}
          architecture: ${_param:opnfv_maas_node04_architecture}
          distro_series: xenial
          hwe_kernel: hwe-16.04
        cmp002:
          interface:
            mac: "00:25:b5:a0:00:6a"
          power_parameters:
            power_address: ${_param:opnfv_maas_node05_power_address}
            power_password: ${_param:opnfv_maas_node05_power_password}
            power_type: ${_param:opnfv_maas_node05_power_type}
            power_user: ${_param:opnfv_maas_node05_power_user}
          architecture: ${_param:opnfv_maas_node05_architecture}
          distro_series: xenial
          hwe_kernel: hwe-16.04
  linux:
    network:
      interface:
        dhcp_interface:
          enabled: true
          name: ${_param:dhcp_interface}
          type: eth
          proto: dhcp
        primary_interface:
          enabled: true
          name: ${_param:primary_interface}
          mtu: ${_param:interface_mtu}
          proto: static
          address: ${_param:infra_maas_node01_address}
          netmask: 255.255.255.0
          type: eth
        pxe_interface:
          enabled: true
          name: ${_param:pxe_interface}
          mtu: ${_param:pxe_interface_mtu}
          proto: static
          address: ${_param:single_address}
          netmask: 255.255.255.0
          type: eth
        external_interface:
          enabled: true
          name: ${_param:external_interface}
          mtu: ${_param:interface_mtu}
          proto: static
          address: ${_param:infra_maas_node01_external_address}
          netmask: 255.255.255.0
          type: eth
