   - module: fuel-plugin-ovs
     module-config-name: fuel-nshovs
     module-config-version: 0.9.0
     module-config-override:
       metadata:
         versions:
           - install_dpdk:
               value: true
             metadata:
               plugin_version: 0.9.0

