   - module: onos
     module-config-name: fuel-onos
     module-config-version: 0.0.3
     module-config-override:
       metadata:
         class: plugin
         default: false
         enabled: true
         label: onos plugin
         toggleable: true
         versions:
         - enable_sfc:
             label: SFC features
             type: checkbox
             value: false
             weight: 13
           metadata:
             hot_pluggable: false
             plugin_version: 0.9.0
             restrictions:
             - cluster:net_provider != 'neutron': Neutron only
             - settings:public_network_assignment.assign_to_all_nodes.value == false: Assign
                 public network to all nodes
         weight: 70

