  - module: fuel-plugin-ovs
    module-config-name: fuel-nshovs
    module-config-version: 0.9.0
    module-config-override:
      metadata:
        versions:
          - install_nsh:
              value: true
            metadata:
              plugin_version: 0.9.0
  - module: opendaylight
    module-config-name: fuel-odl
    module-config-version: 0.9.0
    module-config-override:
      metadata:
        versions:
          - enable_sfc:
              value: true
            metadata:
              plugin_version: 0.9.0

