##############################################################################
# Copyright (c) 2015,2016 Ericsson AB and others.
# jonas.bjurel@ericsson.com
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

############################################################################### # Description:
# This .yaml configuration file defines the configuration of the fuel
# deployment and is passed as an argument to deploy.sh
# eg. deploy.sh -c https://artifact.opnfv.org/fuel/config
# This will make build.sh fetch this configuration file and configure the
# deployment accordingly.
# After the deployment, a copy of this file gets uploaded to fuel:
# /root/deploy-config.yaml, as well as the sha-1 sum of this file:
# /root/deploy-config.sha1
##############################################################################

##############################################################################
# deployment configuration meta-data
deployment-scenario-metadata:
   title: ODL-L2-SFC No-HA deployment
   version: 0.0.4
   created: Feb 10 2016
   comment: Fuel ODL-L2 SFC No HA with Ceph, Ceilometer and Heat Rebased for Fuel10

##############################################################################
# Stack extentions are opnfv added value features in form of a fuel-plugin
# plug-ins listed below will be enabled and configured according to the
# <module-config-base-uri>/<module-config-name>_<module-config-version>.yaml
# It does so by copying the config file to the local plugin config directory
stack-extensions:
  - module: fuel-plugin-ovs
    module-config-name: fuel-nshovs
    module-config-version: 1.0.0
    module-config-override:
      metadata:
        versions:
          - install_nsh:
              value: true
            metadata:
              plugin_version: 1.0.0
  - module: opendaylight
    module-config-name: fuel-odl
    module-config-version: 1.0.0
    module-config-override:
      metadata:
        versions:
          - enable_sfc:
              value: true
            deb_version:
              value: '5.2.0-1'
            metadata:
              plugin_version: 1.0.0
  - module: tacker
    module-config-name: fuel-tacker
    module-config-version: 1.0.0

# Note that the module substitionion does not support arrays
# This is a quick fix
#   - module: opendaylight
#     module-config-name: fuel-odl
#     module-config-version: 0.0.2
#     module-config-override:
#       # Module config overrides
#       rest_api_port:
#         value: '8282'
#       enable_gbp:
#         value: false
#       enable_l3_odl:
#         value: false
#       enable_sfc:
#         value: false

##############################################################################
# By editing the override-config sections below, you can override arbitrary
# configuration name-space settings
dea-override-config:
  nodes:
  - id: 1
    interfaces: interfaces_1
    role: mongo,controller,tacker
  - id: 2
    interfaces: interfaces_1
    role: ceph-osd,opendaylight
  - id: 3
    interfaces: interfaces_1
    role: ceph-osd,compute
  - id: 4
    interfaces: interfaces_1
    role: ceph-osd,compute

dha-override-config:
#  disks:
#    contrail: 500G

##############################################################################
# The verification pipeline may populate the section below with arbitrary
# testing information, which post deploy can be retreived from the fuel master:
# /root/deploy-config.yaml
test:
