##############################################################################
# Copyright (c) 2018 Mirantis Inc., Enea AB and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################
---
classes:
  - cluster.mcp-common-ha.infra.config
  - cluster.mcp-ovs-dpdk-ha.infra
  - cluster.all-mcp-arch-common.infra.config_dpdk_pdf
